### ISSUE TITLE
Murder Mystery Project Review

### ISSUE THREAD

**Issue by gnaww** [Sully8891/pwp-capstones#1]
## Rubric Score
 
### Criteria 1: Valid Python Code
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_
 
No errors!

### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_
 
- Small nitpick, but these 3 properties of TextSample should be using the prepared text as their input
```
self.average_sentence_length = get_average_sentence_length(self.raw_text)
self.word_count_frequency = build_frequency_table(text)
self.ngram_frequency = build_frequency_table(ngram_creator(self.prepared_text))
```

### Criteria 3: Software Architecture
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_
 
Well done here! Functions are used properly and there isn't repeated code!

### Criteria 4: Uses Python Language Features
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_

- A small thing in terms of efficiency in ``frequency_comparison``, instead of adding values to arrays ``appearance`` and ``mutual_appearance``, you can directly add the values together as you iterate through the frequency tables by making those two variables integers instead of arrays! This way you won't have to sum them up again at the end before calculating the comparison score.

### Criteria 5: Produces Accurate Output
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_
 
- ``get_average_sentence_length`` is returning the average character length of each sentences rather than the word length of each sentences! ``for word in sentence:`` is iterating character by character rather than word by word. To iterate word by word you want to split each sentence first by spaces.

### Overall Score: 17/20

Overall very good job on this project! You even went ahead and used Python's regex library, great job figuring out a creative solution on your own! Learning how to find a library/premade solution that will make your job easier and knowing how to read the documentation to figure out how to use it is a very important skill to have and develop!

**Comment by Sully8891** [comment]
Thank you for the very detailed feedback. I appreciate it very much and will make the changes suggested!
